# PERFIL: LOCAL
spring:
  datasource:
    # BD Local (Debe ser la misma a la que apuntan Auth y Onboarding)
    url: jdbc:postgresql://localhost:5432/quhealthy_local
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Dialecto espacial explícito para local
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect

# LOGGING DETALLADO
logging:
  level:
    root: INFO
    com.quhealthy: DEBUG # Ver logs de creación de items
    org.hibernate.SQL: DEBUG # Ver queries geoespaciales

# STORAGE LOCAL (MINIO)
# Guardamos las imágenes en MinIO en lugar de Google Cloud Storage
storage:
  provider: minio

minio:
  # Si corres desde IntelliJ usa localhost
  # Si corres todo en Docker network usa http://minio:9000
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: quhealthy-catalog-images

# CLAVES DUMMY (Para evitar errores al iniciar)
# Debe coincidir con la clave usada en Auth Service para poder validar el token
application:
  security:
    jwt:
      secret-key: local-dev-secret-key-change-in-production-must-match-auth