name: Notification Service Pipeline ðŸ””

on:
  push:
    branches: [ "main" ]
    paths:
      - 'notification_service/**'     # ðŸ‘ˆ Solo si hay cambios en notification_service
      - '.github/workflows/notification-service.yml'
  pull_request:
    paths:
      - 'notification_service/**'

# PERMISOS PARA GCP (OIDC)
permissions:
  contents: read
  id-token: write

jobs:
  call-workflow:
    uses: ./.github/workflows/microservice-pipeline.yml
    with:
      service_name: notification-service
      directory: notification_service
      sonar_project_key: quhealthy-notification-service

      # âœ… 1. Seguridad: Usar su propia identidad
      flags: '--service-account=sa-notification@quhealthy-backend.iam.gserviceaccount.com'

      # âœ… 2. ConfiguraciÃ³n: Variables NO secretas
      # GCP_PROJECT_ID es vital para que el Listener de Pub/Sub encuentre las suscripciones
      extra_env_vars: |
        LOGGING_LEVEL_ROOT=INFO

      # âœ… 3. Secretos (Mantenemos tu lista original)
      env_secrets_mapping: |
        DB_URL=application_db_url:latest
        DB_USER=application_db_user:latest
        DB_PASSWORD=application_db_password:latest
        RESEND_API_KEY=application_resend_key:latest
        JWT_SECRET=application_jwt_secret:latest
        RESEND_FROM_EMAIL=RESEND_FROM_EMAIL:latest
        TWILIO_SID=application_twilio_sid:latest
        TWILIO_TOKEN=application_twilio_token:latest
        TWILIO_PHONE=application_twilio_phone:latest
        FIREBASE_CREDENTIALS=application_firebase_credentials:latest

    secrets:
      # Credenciales de infraestructura (GitHub Secrets)
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
      GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}